[tool.djlint]
profile = "jinja"
require_pragma = false
linter_output_format = "{code}: {message} on line {line} in {filename}"
use_gitignore = true
ignore = "H006,H020,H021,H023,H024,H025,H026,H029,H030,H031,H032,H033,H034,H035,H036,H037,H038,H039,H040,H041,H042,H043,H044,H045,H046,H047,H048,H049,H050,H051,H052,H053,H054,H055,H056,H057,H058,H059,H060,H061,H062,H063,H064,H065,H066,H067,H068,H069,H070,H071,H072,H073,H074,H075,H076,H077,H078,H079,H080,H081,H082,H083,H084,H085,H086,H087,H088,H089,H090,H091,H092,H093,H094,H095,H096,H097,H098,H099,H100"
line_length = 120
indent = 4
indent_html = true
blank_line_after_tag = true

